wordsnum: 5
words:
  - '表示肯定'
  - '回头'
  - '伤害某人'
  - '破坏方块'
  - '放置方块'
  - '杀死一个生物'
  - '合成东西'
  - '手拿一个斧子'
  - '手拿一个镐子'
  - '下蹲'
  - '手拿剑'
  - '低头'
  - '抬头'
  - '挖到铁矿'
  - '挖到煤炭'
  - '挖到金矿'
  - '手拿石剑'
  - '表示否定'
  - '手拿铁剑'
  - '获得铁锭'
  - '获得物品'
  - '死亡'
  - '打死一个玩家'
  - '被一只苦力怕炸死'
  - '被一只僵尸杀死'
  - '被一只小白射♂死'
  - '站到石头上'
  - '站到草方块上'